platform :ios, ‘8.0’
target “yourProjectName” do

pod 'AFNetworking'
pod 'Masonry'
pod 'MJRefresh'
pod ‘MJExtension’
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'TZImagePickerController'
pod 'Bugly'

end
